"""Ender 3-axis "ProbeBot" stage controller for the probot platform.

Refactor of the original ``probebot.py``. Changes versus the original:

* **No work in ``__init__``.** The original connected to the stage and moved to
  the safe position inside the constructor (and printed). Connection + initial
  move now happen in :meth:`startup` / :meth:`home`, keeping the class
  importable and constructable without hardware.
* **Configurable port / geometry.** ``COM3`` and the reference positions are
  constructor arguments.
* Adds :meth:`get_position` (for edge telemetry) and :meth:`move_to_cell`.

Original method names (``probing`` / ``unprobing`` / ``move_to_safeposition``)
are kept as aliases so the GUI's direct calls continue to work.
"""

from __future__ import annotations

import logging
import time

logger = logging.getLogger(__name__)

# Reference positions (from the original probebot.py).
DEFAULT_CELL0_POSITION = [178.4, 74, 52.5]  # probe +10 mm above the glass (y-axis)
DEFAULT_SAFE_POSITION = [0, 170, 100]
NUM_CELLS = 81


class ProbotStage:
    """Control the probot Ender cartesian stage over serial.

    The constructor only stores configuration; call :meth:`startup` to connect.
    A 9x9 (81-cell) sample grid is generated by :meth:`cell_coordinates`.
    """

    def __init__(
        self,
        port: str = "COM3",
        safe_height: float = 80,
        cell0_position: list | None = None,
        safe_position: list | None = None,
    ) -> None:
        """Store stage config (does not connect).

        Args:
            port: Serial COM port of the Ender controller.
            safe_height: Safe travelling height passed to the Ender driver.
            cell0_position: XYZ of cell 1; defaults to the lab reference.
            safe_position: XYZ of the parking position; defaults to the lab reference.
        """
        self.port = port
        self.safe_height = safe_height
        self.cell0_position = list(cell0_position) if cell0_position else list(DEFAULT_CELL0_POSITION)
        self.safe_position = list(safe_position) if safe_position else list(DEFAULT_SAFE_POSITION)
        self.mover = None

    @property
    def is_connected(self) -> bool:
        """Return True once :meth:`startup` has opened the stage."""
        return self.mover is not None

    def startup(self) -> bool:
        """Connect to the Ender controller and move to the safe position."""
        if self.is_connected:
            return True
        try:
            from controllably.Move.Cartesian import Ender

            logger.info("Connecting to Ender stage on %s", self.port)
            self.mover = Ender(port=self.port, safe_height=self.safe_height)
            self.mover.moveTo(self.safe_position)
            logger.info("Stage connected; at initial safe position")
            return True
        except Exception:
            logger.exception("Failed to connect to Ender stage on %s", self.port)
            self.mover = None
            return False

    def shutdown(self) -> bool:
        """Park at the safe position and drop the handle."""
        try:
            if self.is_connected:
                self.move_to_safeposition()
        except Exception:
            logger.exception("Error parking stage during shutdown")
        finally:
            self.mover = None
        return True

    def home(self) -> bool:
        """Move to the safe position (the stage's resting/home pose)."""
        self.move_to_safeposition()
        return True

    def get_position(self) -> dict[str, float]:
        """Return the current stage coordinates as ``{"x","y","z"}``."""
        if not self.is_connected:
            return {"x": 0.0, "y": 0.0, "z": 0.0}
        c = self.mover.coordinates
        return {"x": float(c[0]), "y": float(c[1]), "z": float(c[2])}

    # ------------------------------------------------------------------
    # Motion primitives (ported from probebot.py)
    # ------------------------------------------------------------------

    def cell_coordinates(self) -> list:
        """Generate XYZ coordinates for every cell in the 9x9 grid."""
        logger.debug("Initialising cell positions")
        cell0_position = self.cell0_position
        cells = []
        for cell in range(0, NUM_CELLS):
            for row in range(0, 9):
                for column in range(0, 9):
                    cell = [
                        cell0_position[0] - ((84 / 8) * column),
                        cell0_position[1] - ((0.5 / 8) * row),
                        cell0_position[2] + ((80 / 8)) * row,
                    ]
                    cells.append(cell)
        return cells

    def move_to(self, position) -> None:
        """Move to an absolute XYZ position, waiting out the estimated travel time."""
        current_coordinate = self.mover.coordinates
        x_time = abs(float(current_coordinate[0]) - float(position[0])) * 2 / 84
        y_time = abs(float(current_coordinate[1]) - float(position[1])) * 3 / 75
        z_time = abs(float(current_coordinate[2]) - float(position[2])) * 17 / 80
        movement_wait = x_time + y_time + z_time

        logger.debug("Moving stage to %s (wait %.2fs)", position, movement_wait)
        self.mover.moveTo(position)
        time.sleep(movement_wait)

    def move_to_cell(self, cell_number: int) -> None:
        """Move to a cell by 1-based cell number."""
        cells = self.cell_coordinates()
        self.move_to(cells[cell_number - 1])

    def probe(self) -> None:
        """Lower the probe 10 mm to make contact."""
        logger.debug("Probing")
        self.mover.moveBy([0, -10, 0])
        time.sleep(0.5)

    def unprobe(self) -> None:
        """Raise the probe 10 mm to release contact."""
        logger.debug("Unprobing")
        self.mover.moveBy([0, 10, 0])

    def move_to_cell1(self) -> None:
        """Move to cell 1 and wait for the stage to settle."""
        self.mover.moveTo(self.cell0_position)
        time.sleep(2)

    def move_to_cell81(self) -> None:
        """Move to cell 81 and wait for the stage to settle."""
        cells = self.cell_coordinates()
        self.mover.moveTo(cells[80])
        time.sleep(2)

    def move_to_safeposition(self) -> None:
        """Move to the parking/safe position and wait for the stage to settle."""
        self.mover.moveTo(self.safe_position)
        time.sleep(2)

    # Backwards-compatible aliases for the GUI's existing calls.
    probing = probe
    unprobing = unprobe


StageProbot = ProbotStage
